### ISSUE TITLE
关于训练数据集

### ISSUE THREAD

**Issue by MaxwellJean** [ForJadeForest/ImageSearchLightningCLIP#3]
您好，想请问下有对应的中文训练数据集嘛

**Comment by ForJadeForest** [comment]
目前公开在huggingface上的中文图像文本对数据较少，可能需要自己构建。不过也有人训练过中文CLIP，或许可以查一下别人是否分享了数据集。

- 同时蒸馏的teacher最好替换为别人预训练好的中文CLIP。
- 不过本项目是对image和text两个分支分开蒸馏，可以考虑直接使用任意的中文的文本数据进行蒸馏。不过如果图像和文本数据集不存在对齐的数据的话可能会导致一定的性能下降（没有经过验证）。
